# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines bellow are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    id: cli
    goos:
      - linux
      - windows
      - darwin

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  draft: true
  prerelease: auto
  name_template: "{{.ProjectName}}-v{{.Version}}-{{.Date}}"

dockers:
  - image_templates:
      - "ghcr.io/cxjava/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "ghcr.io/cxjava/{{ .ProjectName }}:latest-amd64"
    dockerfile: Dockerfile
    use: buildx
    ids:
      - cli
    build_flag_templates:
      - --platform=linux/amd64
  - image_templates:
      - "ghcr.io/cxjava/{{ .ProjectName }}:{{ .Version }}-arm64v8"
      - "ghcr.io/cxjava/{{ .ProjectName }}:latest-arm64v8"
    goarch: arm64
    dockerfile: Dockerfile
    use: buildx
    ids:
      - cli
    build_flag_templates:
      - --platform=linux/arm64/v8
  - image_templates:
      - "ghcr.io/cxjava/{{ .ProjectName }}:{{ .Version }}-armv7"
      - "ghcr.io/cxjava/{{ .ProjectName }}:latest-armv7"
    goarch: arm
    goarm: 7
    dockerfile: Dockerfile
    use: buildx
    ids:
      - cli
    build_flag_templates:
      - --platform=linux/arm/v7

docker_manifests:
  - name_template: ghcr.io/cxjava/{{ .ProjectName }}:{{ .Version }}
    image_templates:
      - ghcr.io/cxjava/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/cxjava/{{ .ProjectName }}:{{ .Version }}-arm64v8
      - ghcr.io/cxjava/{{ .ProjectName }}:{{ .Version }}-armv7
  - name_template: ghcr.io/cxjava/{{ .ProjectName }}:latest
    image_templates:
      - ghcr.io/cxjava/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/cxjava/{{ .ProjectName }}:{{ .Version }}-arm64v8
      - ghcr.io/cxjava/{{ .ProjectName }}:{{ .Version }}-armv7
