name: Deploy

on:
  # push:
  #   branches: [main]
  # pull_request:
  #   branches: [main]
  # release:
  #   types: [created]
  workflow_dispatch:
    inputs:
      bump_type:
        description: 'Bump tag type: major, minor, patch. default: minor'
        required: true
        default: 'minor'

jobs:
  build-clash:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Dashboard code
        uses: actions/checkout@v4
        with:
          repository: Dreamacro/clash-dashboard

      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: pnpm

      - name: Install package and build
        run: |
          pnpm install --frozen-lockfile
          pnpm build

      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: clash
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

  build-yacd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: haishanh/yacd

      - uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: true

      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: pnpm

      - name: Build
        run: pnpm build

      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: yacd
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
  go-build:
    runs-on: ubuntu-latest
    name: go build
    needs: [build-yacd, build-clash]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: cxjava/clash-ui
          ref: clash
          path: clash
      - uses: actions/checkout@v4
        with:
          repository: cxjava/clash-ui
          ref: yacd
          path: yacd
      - uses: actions/setup-go@v4
        with:
          go-version: stable
      - name: Environment
        run: |
          go mod tidy
          rm -rf ./yacd/.git
          rm -rf ./clash/.git
      - name: Bump tag version
        id: bumpTag
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DRY_RUN: true
          DEFAULT_BUMP: "${{ github.event.inputs.bump_type }}" 
      - name: Bump tag locally
        run: git tag ${{ steps.bumpTag.outputs.new_tag }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean --skip=validate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
