name: Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [created]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Dashboard code
        uses: actions/checkout@v4
        with:
          repository: Dreamacro/clash-dashboard

      - uses: pnpm/action-setup@v2
        with:
          version: latest
      
      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: pnpm

      - name: Install package and build
        run: |
          pnpm install --frozen-lockfile
          pnpm build
      
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: clash
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: haishanh/yacd

      - uses: pnpm/action-setup@v2
        with:
          version: latest
      
      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: pnpm

      - name: Build
        run: pnpm build
    
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: yacd
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
